apiVersion: v1
kind: Service
metadata:
  name:  vue-testapp
  namespace: dev
spec:
  selector:
    app: vue-testapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
